### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by SomeoneThatYouDontKnow** [xxxOMA/MonsoonRip#6]
I tried to copy the 1.8.9 into the mcp but the problem is that everytime I run it an auth screen pops up, so it won't let me setup and test in a mcp world, any fixes?

**Comment by Fizzify** [comment]
Go to Authentication.java class and replace the method "run", https://pastebin.com/UyfiHTuz then just run the client and click the login button without putting any details.

**Comment by SomeoneThatYouDontKnow** [comment]
Thanks, but when I do it and run it this error pops out. I am using MCP 918 (1.8.8).

`Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:3043)
	at net.minecraft.client.main.Main.main(Main.java:39)
	at Start.main(Start.java:11)`

**Comment by SomeoneThatYouDontKnow** [comment]
I will really appreciate it if you help me.

**Comment by EZZZZ1234** [comment]
Yeah, that's the error I'm getting too when 'Launching'.

**Comment by xxxOMA** [comment]
This repo is meant for people to skid the code and not compile it

**Comment by SomeoneThatYouDontKnow** [comment]
sorry
